### ISSUE TITLE
['id'] to ['dataId'], ["cameraConfigUrl"] to ["cameraConfig"]["url"]

### ISSUE THREAD

**Issue by ClementLeBihan** [xtreme1-io/xtreme1-sdk#2]
Hi,
With xtreme1 v0.8, the export has replaced id to dataId, cameraConfigUrl to ["cameraConfig"]["url"].
Can you update the xtreme1-sdk to make it work with v8.0 ?

**Comment by ShirleySprite** [comment]
All fixed now, the issue was in the 'to_kitti' function.

**Comment by ClementLeBihan** [comment]
Thanks @ShirleySprite
