### ISSUE TITLE
Inaccurate 3D bounding box - Converting from KITTI to Xtreme1

### ISSUE THREAD

**Issue by l1997i** [xtreme1-io/xtreme1-sdk#3]
Thank you very much for your work. This is the best annotation tool and SDK I have found so far.

I use the following command to convert the KITTI dataset (attachment: [test1_kitti_raw.zip](https://github.com/xtreme1-io/xtreme1-sdk/files/14361612/test1_kitti_raw.zip)) into xtreme1 format (resulting file: [test1_to_xtreme1.zip](https://github.com/xtreme1-io/xtreme1-sdk/files/14361614/test1_to_xtreme1.zip)),

```bash
python script_ctl.py --mode import --src data/test1_kitti_raw/ --dst data/test1_to_xtreme1 --fmt kitti
```

Then, I upload the data to the xtreme1 local server. For 2D images, the ground truth labels seem to have been converted very correctly. 

However, for the 3D bounding boxes, I think that

1. the calibration parameters might have been converted incorrectly, or 
2. there was an error in the conversion of the 3D bounding boxes. 

As indicated by the blue arrows in Figures 1 and 2, the 3D ground truth is completely incorrect, and the 3DBBox seems to have an offset towards the y-axis.

![2](https://github.com/xtreme1-io/xtreme1-sdk/assets/35445094/b7f6d9ee-2505-4489-9eab-e7a4196977a2)
![1](https://github.com/xtreme1-io/xtreme1-sdk/assets/35445094/bb67e52e-c401-4ce5-8544-c3b3d0bb465e)

**Comment by ShirleySprite** [comment]
Thank you for reporting the bug. The issue has been fixed.
![camera](https://github.com/xtreme1-io/xtreme1-sdk/assets/108784156/ed53e510-73bd-41ef-bc80-be694067fa76)
![lidar](https://github.com/xtreme1-io/xtreme1-sdk/assets/108784156/f0f88de0-c781-4617-b6a0-288ba4286567)
